# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-39640-tuxedo-2024/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu7ev-ffvc1156-3-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include /home/chris/AMD-FPGA/2025.2/data/rsb/busdef {
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_activeLayerProcessor.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_exp2Frac.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_inputEmbedding.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_invSqrtF.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_log2Decompose.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_logitsProjector.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_rmsNormSeq.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_roundRobinGrant.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_roundRobinGrant_0.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_roundRobinGrant_1.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_roundRobinGrant_2.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_rowComputeUnit.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_rowComputeUnit_0.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_rowComputeUnit_1.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_rowComputeUnit_2.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_scalePow2F.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_scalePow2F_0.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_tokenSampler.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_trueDualPortBlockRamWrapper.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/LLaMa2_Decoder_Decoder_topEntity_trueDualPortBlockRamWrapper_0.v
      /home/chris/Projects/llama2.clash/temp/clash-verilog-model-110m/full/LLaMa2.Decoder.Decoder.topEntity/decoder.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top decoder
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-39640-tuxedo-2024/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
